### ISSUE TITLE
infografia_Hilos

### ISSUE THREAD

**Issue by williamgl3** [SistemasTecTlaxiaco/infografia-de-hilos-williamgl3#2]
https://drive.google.com/file/d/1MJSPx1wk9H8oBBexcV3Ljg61rAtwSsIv/view?usp=sharing

**Comment by ArcangelGC** [comment]
Recibo infografia. ✍🏼
En base a la rúbrica y a cómo debe de ser una infografia hacemos las siguientes observaciones.

Observaciones:

El tipo de color de fuente en las referencias no es lo más indicado pero es legible.
Tiene buena información y resumida
Posee una conclusion
Posee referencias

La calificación es de 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
